
```{r}
# Loading necessary libraries
library(readr)
library(arrow)
library(caret)
library(data.table)
library(magrittr)
library(dplyr)
library(tidyverse)
```

```{r}
# URLs for the static house, weather, and energy usage datasets.
static_data_url <- "https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/static_house_info.parquet"
weather_data_url <- "https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/weather/2023-weather-data/G4500010.csv"
energy_usage_url <- "https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/2023-houseData/102063.parquet"
metadata_url <- "https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/data_dictionary.csv"
# Reading the datasets
df_static <- read_parquet(static_data_url)
df_weather <- read_csv(weather_data_url)
df_energy <- read_parquet(energy_usage_url)
df_metadata <- read_csv(metadata_url)
```
```{r}
#subsetting the required columns from the house data
static_subset_data <- df_static[c("bldg_id","in.county","in.sqft", "in.ducts","in.geometry_building_type_acs" , "in.geometry_stories", "in.geometry_wall_type" ,"in.geometry_story_bin"  , "in.geometry_wall_exterior_finish" ,"in.hvac_cooling_type","in.insulation_wall" ,"in.lighting","in.natural_ventilation" ,"in.occupants","in.orientation","in.roof_material" ,"in.vacancy_status" ,"in.vintage_acs","in.windows","in.building_america_climate_zone" )]
static_subset_data
```

```{r}
#Applying the filter criteria using "in.sqft" and "in.building_america_climate_zone columns"
houses_sqft_zone <- static_subset_data %>% filter(in.sqft < 900 & in.building_america_climate_zone =="Hot-Humid" )
houses_sqft_zone
```


```{r}
# Using unique() function to get all unique values of bldg_id
all_bldg_ids <- unique(houses_sqft_zone$bldg_id)

# Printing the extracted unique building IDs
print(all_bldg_ids)

```



```{r}
#Storing the building ids in "bldg_ids"
bldg_ids <- c("670", "4561", "17496", "24120", "24918", "29895", "32115", "36877", "39235", "43131", "43309", "55360", "62771", "67881", "91114", "103686", "126042", "136725", "139608", "144853", "153528", "165581", "179042", "180931", "185397", "186846", "196102", "197153", "197167", "212450", "228607", "247057", "266455", "272780", "278750", "281994", "282932", "290839", "291688", "293273", "306901", "307298", "313003", "320346", "365040", "366064", "369817", "378367", "379073", "379141", "384753", "387224", "387597", "399743", "400010", "406547", "407645", "409139", "419219", "433435", "439684", "450950", "456936", "458499", "461249", "471199", "474709", "475174", "483565", "488726", "491499", "501618", "522537", "531426", "534961", "536353", "537775", "544553")

# Initialize an empty list to store results for each building
all_building_consumption <- list()
#Creating a for loop
for (bldg_id in bldg_ids) {
  # Constructing URL for energy usage data for the current building ID
  energy_usage_url <- paste0("https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/2023-houseData/", bldg_id, ".parquet")
  
  # Reading energy usage data for the current building into df_energy
  df_energy <- read_parquet(energy_usage_url)
  
  # Selecting the necessary columns for energy consumption
  selected_columns <- c(
    "out.electricity.cooling.energy_consumption",
    "out.electricity.refrigerator.energy_consumption",
    "out.electricity.clothes_washer.energy_consumption",
    "out.electricity.dishwasher.energy_consumption",
    "out.electricity.clothes_dryer.energy_consumption",
    "out.electricity.hot_water.energy_consumption",
    "out.natural_gas.hot_water.energy_consumption",
    "out.propane.hot_water.energy_consumption",
    "out.electricity.lighting_interior.energy_consumption",
    "out.electricity.plug_loads.energy_consumption",
    "out.natural_gas.heating.energy_consumption",
    "out.propane.heating.energy_consumption"
  )
  
  # Subsetting the energy data to selected columns
  energy_subset <- df_energy[, selected_columns]
  
  # Calculating per hour consumption for the current building
  energy_subset$per_hour_consumption <- rowSums(energy_subset, na.rm = TRUE)
  
  # Combining time and per_hour_consumption columns
  hr_consumption_data <- data.frame(time = df_energy$time, per_hour_consumption = energy_subset$per_hour_consumption)
  hr_consumption_data
  # Converting to data frame
  hr_consumption_data <- as.data.frame(hr_consumption_data)
  
  # Rename columns
  colnames(hr_consumption_data) <- c("time", "per_hour_consumption")
  
  # Grouping consumption data into 6-hour intervals and summarize
  summarized_data <- hr_consumption_data %>%
    mutate(group_id = rep(1:(n() %/% 6 + 1), each = 6, length.out = n())) %>%
    group_by(group_id) %>%
    summarise(
      consumption_per_6hrs = sum(per_hour_consumption),
      date_time = first(time) 
    )
  
  # Storing summarized data for the current building
  all_building_consumption[[bldg_id]] <- summarized_data
}

```

```{r}
all_building_consumption
```
```{r}
for (bldg_id in names(all_building_consumption)) {
  # Replace 'group_id' with the building ID "bldg_id" for each dataframe
  all_building_consumption[[bldg_id]]$group_id <- as.integer(bldg_id)
}
all_building_consumption
```

```{r}
#Removing unnecessary elements.
all_building_consumption<- all_building_consumption[-79]
combined_consumption_dataset <- bind_rows(all_building_consumption)
combined_consumption_dataset <- combined_consumption_dataset %>%
                     rename(bldg_id = group_id)
combined_consumption_dataset
#viewing the dataset
view(combined_consumption_dataset)
```
```{r}

# Converting the "date_time" column to only "date" format
combined_consumption_dataset$date <- as.Date(combined_consumption_dataset$date_time)

# Removing the extra date_time column as it is not needed.
combined_consumption_dataset <- combined_consumption_dataset[, -which(names(combined_consumption_dataset) == "date_time")]

# Printing the modified dataset
print(combined_consumption_dataset)

```


```{r}

# Using unique() function to get all unique county codes.
all_county_codes <- unique(houses_sqft_zone$in.county)

# Printing the extracted unique county codes.
print(all_county_codes)

```


```{r}
#Reading the unique county codes into "county_codes".
county_codes <- c( "G4500350", "G4500510", "G4500130", "G4500190", "G4500150", "G4500430", "G4500110", "G4500290", "G4500090", "G4500490") 
# Initialize an empty list to store results for each county.
all_county_weather <- list()

# Iterating over each county code
for (county_code in county_codes) {
  # Constructing URL for weather data for the current county
  weather_url <- paste0("https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/weather/2023-weather-data/", county_code, ".csv")
  
  # Reading the CSV file from the URL into "weather_data"
  weather_data <- read_csv(weather_url)
  
  # Selecting the required columns from "weather_data"
  subset_data <- weather_data %>%
    select(`Dry Bulb Temperature [°C]`, `Wind Speed [m/s]`, `Relative Humidity [%]`, date_time)
  
  # Adding an index to group every 6 rows
  subset_data <- subset_data %>%
    mutate(group_index = ceiling(row_number() / 6))
  
  # Calculating mean for each group
  mean_data <- subset_data %>%
    group_by(group_index) %>%
    summarise(
      Mean_Temperature = mean(`Dry Bulb Temperature [°C]`, na.rm = TRUE),
      Mean_Wind_Speed = mean(`Wind Speed [m/s]`, na.rm = TRUE),
      Mean_Relative_Humidity = mean(`Relative Humidity [%]`, na.rm = TRUE),
      date_time = first(date_time) 
    ) 
  # Storing mean weather data for the current county
  all_county_weather[[county_code]] <- mean_data
}

print(all_county_weather)
```

```{r}

# List of county names
county_names <- c("G4500350", "G4500510", "G4500130", "G4500190", "G4500150", 
                   "G4500430", "G4500110", "G4500290", "G4500090", "G4500490")

# Loop through each dataset in the list
for (i in seq_along(all_county_weather)) {
  # Extract the current dataset
  current_data <- all_county_weather[[i]]
  
  # Replace the group_index column with the corresponding county name
  current_data$group_index <- county_names[i]
  
  # Update the dataset in the list
  all_county_weather[[i]] <- current_data
}

# Updated list with group_index replaced by county names
all_county_weather
```

```{r}
# Combine all datasets in the list into a single dataframe
combined_weather_data <- bind_rows(all_county_weather)
# Loop through each dataset in the list
for (i in seq_along(all_county_weather)) {
  # Rename the "group_index" column to "in.county"
  all_county_weather[[i]] <- rename(all_county_weather[[i]], in.county = group_index)
}
# Printing and Viewing the combined dataset
print(combined_weather_data)
view(combined_weather_data)
```

```{r}
# Converting the "date_time" column to Date class
combined_weather_data$date_time <- as.Date(combined_weather_data$date_time)

# Viewing the modified dataset
combined_weather_data
```

```{r}
library(dplyr)
# Renaming the column name
combined_weather_data <- combined_weather_data %>%
  rename(date = date_time)

# Viewing the modified dataset
combined_weather_data

```

```{r}
#merging house data with the energy data
merged_dataset <- merge(combined_consumption_dataset, houses_sqft_zone, by = "bldg_id", all.x = TRUE)
merged_dataset
#Printing the first 6 rows of the merged dataset.
head(merged_dataset)
```


```{r}
#Merging all the three datasets
final_merged_dataset <- merge(merged_dataset, combined_weather_data, by = "date", all.x = TRUE)
final_merged_dataset
```


#Exploring the graphs using various criteria.
```{r}
#1.What is the county wise energy consumption?
#Loading the "ggplot2" library.
library(ggplot2)
ggplot(final_merged_dataset, aes(x = final_merged_dataset$in.county.x, y = final_merged_dataset$consumption_per_6hrs, fill = in.county.x)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Energy Consumption per County",
       x = "County",
       y = "Total Energy Consumption") + theme_minimal() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5,hjust=1))
```

```{r}
#2.How does temperature effect the energy consumption?
ggplot(final_merged_dataset, aes(x = final_merged_dataset$Mean_Temperature, y = final_merged_dataset$consumption_per_6hrs)) +
  geom_point(size = 3, color = "blue") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(title = "Temperature vs. Energy Consumption",
       x = "Temperature (Celsius)",
       y = "Energy Consumption") + theme_minimal() #Has a positive correlation
```

```{r}
#3. Find the building with maximum power consumption in each county.
# Load required library
library(dplyr)

all_county_codes_final <- unique(final_merged_dataset$in.county.x)
all_county_codes_final
# Filter data for specific counties
counties_to_search <- c("G4500350", "G4500510", "G4500130", "G4500190", "G4500150", 
                   "G4500430", "G4500110", "G4500290", "G4500090","G4500490")

filtered_data <- final_merged_dataset %>%
  filter(in.county.x %in% counties_to_search)

max_power_buildings <- filtered_data %>%
  group_by(in.county.x) %>%
  top_n(1, consumption_per_6hrs) %>%
  ungroup()

# Print the result
max_power_buildings

max_power_buildings$bldg_id <- as.factor(max_power_buildings$bldg_id)

# Plot with ggplot
ggplot(max_power_buildings, aes(x = bldg_id, y = consumption_per_6hrs, fill = "orange")) +
  geom_bar(stat = "identity") +  # Create a bar chart with the values as heights
  labs(
    x = "Building",
    y = "Maximum Power Consumption",
    title = "Building with Maximum Power Consumption"
  ) +
  theme_minimal()

```

```{r}
#4. Create a ggplot object for the daily energy consumption trend.
library(ggplot2)
library(dplyr)
library(lubridate) 

# Aggregate energy consumption by date
daily_energy_consumption <- final_merged_dataset %>%
  group_by(Date = as.Date(date)) %>%
  summarize(DailyEnergyConsumption = sum(consumption_per_6hrs, na.rm = TRUE))

ggplot(daily_energy_consumption, aes(x = Date, y = DailyEnergyConsumption)) +
  geom_line(color = "blue") + 
  labs(
    x = "Date",
    y = "Daily Energy Consumption",
    title = "Daily Energy Consumption Trend"
  ) +
  theme_minimal()


```

```{r}
#5. How the energy consumption varies with sq.ft?

library(ggplot2)

# Aggregate consumption_per_6hrs by in.sqft
agg_data <- aggregate(consumption_per_6hrs ~ in.sqft, data = final_merged_dataset, FUN = mean)

# Plotting bar graph with blue color
ggplot(agg_data, aes(x = in.sqft, y = consumption_per_6hrs)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(x = "Square Footage (in sqft)",
       y = "Mean Consumption per 6 Hours",
       title = "Mean Consumption by Square Footage")

```

```{r}
#6. How the energy consumption varies with wall type of the house?

library(ggplot2)

ggplot(final_merged_dataset, aes(x = in.geometry_wall_type, y = consumption_per_6hrs, fill = factor(in.geometry_wall_type))) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  labs(
    x = "Wall Type",
    y = "Mean Consumption per 6 Hours",
    fill = "Wall Type",
    title = "Mean Consumption per 6 Hours by Wall Type"
  ) +
  theme_minimal()

```

```{r}
#7. How the energy consumption varies with insulation wall of the house?
{r}
library(ggplot2)

ggplot(final_merged_dataset, aes(x = in.insulation_wall, y = consumption_per_6hrs, fill = factor(in.insulation_wall))) +
  geom_bar(stat = "summary", fun = "mean", position = position_dodge(width = 0.9)) + 
  labs(
    x = "Insulation Wall",
    y = "Mean Consumption per 6 Hours",
    fill = "Insulation Wall",
    title = "Mean Consumption by Insulation Wall"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```

```{r}
#8. How the energy consumption varies with lighting of the house?
library(ggplot2)

ggplot(final_merged_dataset, aes(x = in.lighting, y = consumption_per_6hrs, fill = factor(in.lighting))) +
  geom_bar(stat = "summary", fun = "mean", position = position_dodge(width = 0.9)) + 
  labs(
    x = "Lighting",
    y = "Mean Consumption per 6 Hours",
    fill = "Lighting",
    title = "Mean Consumption by Lighting"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 


```

```{r}
#9. How the energy consumption varies with windows of the house?
library(ggplot2)

ggplot(final_merged_dataset, aes(x = in.windows, y = consumption_per_6hrs, fill = factor(in.windows))) +
  geom_bar(stat = "summary", fun = "mean", position = position_dodge(width = 0.9)) +
  labs(
    x = "Windows",
    y = "MeanConsumptionper6Hrs",
    fill = "Windows",
    title = "Mean Consumption Vs. Windows"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 75, hjust = 1))
```

```{r}
#10. How the energy consumption varies with exterior wall finish of the house?
library(ggplot2)

ggplot(final_merged_dataset, aes(x = in.geometry_wall_exterior_finish, y = consumption_per_6hrs, fill = factor(in.geometry_wall_exterior_finish))) +
  geom_bar(stat = "summary", fun = "mean", position = position_dodge(width = 0.9)) +
  labs(
    x = "Exterior Wall Finish",
    y = "Mean Consumption per 6 Hours",
    fill = "Exterior Wall Finish",
    title = "Mean Consumption by Exterior Wall Finish"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
#11. How the energy consumption varies with the cooling type of the house?

library(ggplot2)

ggplot(final_merged_dataset, aes(x = in.hvac_cooling_type, y = consumption_per_6hrs, fill = factor(in.hvac_cooling_type))) +
  geom_bar(stat = "summary", fun = "mean", position = position_dodge(width = 0.9)) +
  labs(
    x = "Cooling Type",
    y = "Mean Consumption per 6 Hours",
    fill = "Cooling Type",
    title = "Mean Consumption by HVAC Cooling Type"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

